TypeError: __init__(): incompatible constructor arguments.
 Need to remove parameter "model.get_texture_coordinates()".

File "C:/Users/wq/eos/python/demo.py", line 15, in main
    model.get_texture_coordinates())
TypeError: __init__(): incompatible constructor arguments.